__FREQUENCY__ = ["millihertz", "mhz", "mHz", "centihertz", "chz", "cHz", "decihertz", "dhz", "dHz",
                 "hertz", "hz", "Hz", "decahertz", "dahz", "daHz", "hectohertz", "hhz", "hHz", "kilohertz", "khz",
                 "kHz", "megahertz", "MHz", "gigahertz", "ghz", "GHz", "terahertz", "thz", "THz", "petahertz", "phz",
                 "PHz"]

__WAVELENGTH__ = ["nm",
                  "um",
                  "mm",
                  "cm",
                  "dm",
                  "m",
                  "km",
                  "nanometers",
                  "micrometers",
                  "millimeters",
                  "centimeter",
                  "decimeters",
                  "meters",
                  "kilometers",

                  "nanometer",
                  "micrometer",
                  "millimeter",
                  "centimeters",
                  "decimeter",
                  "meter",
                  "kilometer"]
